### ISSUE TITLE
Wrong emphasize asciidoc fragment leads to Exception

### ISSUE THREAD

**Issue by ascheman** [aim42/htmlSanityCheck#342]
# Problem

An [asciidoc fragment](https://github.com/jreleaser/jreleaser.github.io/blob/38116a63bc33ddbb0876f1554544dc8a2b196b5c/docs/modules/tools/pages/jreleaser-ant.adoc?plain=1#L733-L733) like the following, currently leads to an exception (see below) when rendered as HTML.

```asciidoc
Executes the xref:concepts:workflow.adoc#_catalog_[Catalog] workflow step.
```

# Exception

```
org.aim42.htmlsanitycheck.tools.Web$InvalidUriSyntaxException: java.net.URISyntaxException: Illegal character in fragment at index 26: ../concepts/workflow.html#<em>catalog</em>
        at org.aim42.htmlsanitycheck.tools.Web.isLocalResource(Web.java:224)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.aim42.htmlsanitycheck.check.MissingLocalResourcesChecker.check(MissingLocalResourcesChecker.java:54)
...
```

# Expected behaviour

The problem should be properly reported instead of an exception thrown.

# Background

AsciiDoctor renders the code above as 

```html
<p>Executes the <a href="../concepts/workflow.html#<em>catalog</em>" class="xref page">Catalog</a> workflow step.</p>
```

The href in this case does not contain a correct  URI reference according to [RFC-2396](https://www.ietf.org/rfc/rfc2396.txt] which is the base for Java's URI class implementation: Its [`fragment`](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5) (identifier) must not contain `<` (and some other characters).

**Comment by ascheman** [comment]
Asked in Antora Zulip chat [whether this is an AsciiDoctor bug](https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/Wrong.20.28autom.2E.29.20anchor.20usage.20may.20lead.20to.20RFC.202396.20violation).
