### ISSUE TITLE
Exception in ain42 check

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#70]
MadZorg42:aim42-guide gstarke$ gradle htmlSanityCheck
...
:copyImages
:htmlSanityCheck
buildfile-info
allFilesToCheck[/Users/gstarke/projects/aim42/aim42-guide/build/docs/index.html]
:htmlSanityCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':htmlSanityCheck'.
> java.net.URISyntaxException: Illegal character in fragment at index 8: #Context Analysis

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by gernotstarke** [comment]
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 8: #Context Analysis
	at org.aim42.htmlsanitycheck.html.URLUtil.isLocalResource(URLUtil.groovy:40)
	at org.aim42.htmlsanitycheck.html.URLUtil$isLocalResource$1.call(Unknown Source)
	at org.aim42.htmlsanitycheck.check.MissingLocalResourcesChecker$_check_closure1.doCall(MissingLocalResourcesChecker.groovy:36)
	at org.aim42.htmlsanitycheck.check.MissingLocalResourcesChecker.check(MissingLocalResourcesChecker.groovy:35)
	at org.aim42.htmlsanitycheck.check.Checker.performCheck(Checker.groovy:46)
	at org.aim42.htmlsanitycheck.check.Checker$performCheck.call(Unknown Source)
	at org.aim42.htmlsanitycheck.AllChecksRunner.missingLocalResourcesCheck(AllChecksRunner.groovy:214)

**Comment by gernotstarke** [comment]
first iteration: fix bug in aim42... (blank within label)

**Comment by gernotstarke** [comment]
second iteration: before we check if an href is local or remote, we have to check if it's valid (meaning: does it consists only of legal chars?)

**Comment by gernotstarke** [comment]
added regression test
